apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-ui-deployment
  namespace: smart-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-ui
  template:
    metadata:
      labels:
        app: smart-ui
    spec:
      containers:
        - name: smart-ui
          image: smart-ui:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: EDGE_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: smart-platform-configmap
                  key: smart-edge-service-external-url
            - name: LOTTERY_SERVICE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: smart-platform-configmap
                  key: smart-lottery-service-external-url
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
