apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-edge-service-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/logs/smart-edge-service-logs-k8s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-edge-service-logs-pvc
  namespace: smart-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smart-lottery-service-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/logs/smart-lottery-service-logs-k8s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smart-lottery-service-logs-pvc
  namespace: smart-platform
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
