apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-platform-configmap
  namespace: smart-platform
data:
  smart-lottery-service-url: smart-lottery-service-service:8081
  smart-edge-service-external-url: http://smart-egde-service.com
  smart-lottery-service-external-url: http://smart-lottery-service.com
