apiVersion: v1
kind: Service
metadata:
  name: smart-lottery-service-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: smart-lottery-service
  ports:
    - protocol: TCP
      port: {{ .Values.lotteryService.port }}
      targetPort: {{ .Values.lotteryService.port }}
