apiVersion: v1
kind: Service
metadata:
  name: smart-ui-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: smart-ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
