apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-lottery-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-lottery-service
  template:
    metadata:
      labels:
        app: smart-lottery-service
    spec:
      containers:
        - name: smart-lottery-service
          image: smart-lottery-service:1.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: JAVA_ARGS
              value: "-Xms256m -Xmx512m -XX:+UseContainerSupport"
