@startuml
package "Level 0" {
[service] as service
}
package "Level 1" {
[web] as web
[bet-dao] as bet_dao
[db-dao] as db_dao
}
package "Level 2" {
[application] as application
}
package "Level 3" {
[integration-test] as integration_test
[release] as release
}
web --> service
db_dao --> service
bet_dao --> service
application --> web
application --> db_dao
application --> bet_dao
integration_test --> application
release --> application
@enduml