services:
  lottery-service:
    image: smart-lottery-service:1.0-SNAPSHOT
    container_name: smart-lottery-service
    hostname: smart-lottery-service
    ports:
      - "8081:8081"
    volumes:
      - ./logs/smart-lottery-service-prod/:/app/logs/
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  edge-service:
    image: smart-edge-service:1.0-SNAPSHOT
    container_name: smart-edge-service
    hostname: smart-edge-service
    ports:
      - "8080:8080"
    volumes:
      - ./logs/smart-edge-service-prod/:/app/logs/
    environment:
      - LOTTERY_SERVICE_BASE_URL=smart-lottery-service:8081
      - SPRING_PROFILES_ACTIVE=prod