version: '3.7'
services:
  lottery-service:
    image: lottery-service:1.0-SNAPSHOT
    container_name: lottery-service
    hostname: lottery-service
    ports:
      - "8081:8081"
    volumes:
      - ./logs/lottery-service-prod/:/smart/share/lottery/logs/
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  edge-service:
    image: edge-service:1.0-SNAPSHOT
    container_name: edge-service
    hostname: edge-service
    ports:
      - "8080:8080"
    volumes:
      - ./logs/edge-service-prod/:/smart/share/edge/logs/
    environment:
      - LOTTERY_SERVICE_BASE_URL=lottery-service:8081
      - SPRING_PROFILES_ACTIVE=prod