apiVersion: v1
kind: Service
metadata:
  name: smart-edge-service-service
  namespace: smart-platform
spec:
  selector:
    app: smart-edge-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
